using ECommerce.GrpcContracts.Products;
using Grpc.Core;
using Microsoft.Extensions.Logging;
using OrderService.Contracts.DTOs;
using OrderService.Contracts.ExternalServices;
using System.Globalization;

namespace OrderService.Infrastructure.GrpcClients
{
    // ============================================================================
    // gRPC Client Implementation for ProductService
    // ----------------------------------------------------------------------------
    // This class:
    //   - Lives in OrderService.Infrastructure
    //   - Implements IProductServiceClient
    //   - Communicates with ProductService via gRPC
    //
    // Responsibilities:
    //   - Call ProductService gRPC endpoints
    //   - Pass authorization metadata (JWT)
    //   - Convert protobuf messages to OrderService DTOs
    // ============================================================================
    public sealed class ProductServiceGrpcClient : IProductServiceClient
    {
        private readonly ProductGrpc.ProductGrpcClient _client;
        private readonly ILogger<ProductServiceGrpcClient> _logger;

        // ------------------------------------------------------------------------
        // Constructor
        // ------------------------------------------------------------------------
        // ProductGrpcClient is generated by gRPC tooling.
        // ILogger is injected by ASP.NET Core DI.
        public ProductServiceGrpcClient(
            ProductGrpc.ProductGrpcClient client,
            ILogger<ProductServiceGrpcClient> logger)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        // ============================================================================
        // 1. GET SINGLE PRODUCT BY ID
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Convenience method for fetching a single product
        //
        // NOTE:
        //   - Internally delegates to bulk GetProductsByIdsAsync
        //   - Keeps logic DRY and consistent
        // ============================================================================
        public async Task<ProductDTO?> GetProductByIdAsync(Guid productId)
        {
            _logger.LogInformation(
                "Calling ProductService.GetProductById via gRPC. product_id={ProductId}",
                productId);

            // Interface does not accept token here.
            // If ProductService requires auth, either:
            //   - Change interface to accept token, OR
            //   - Keep REST fallback for this method
            var list = await GetProductsByIdsAsync(
                new List<Guid> { productId },
                accessToken: string.Empty);

            var product = list?.FirstOrDefault();

            _logger.LogInformation(
                product == null
                    ? "Product not found. product_id={ProductId}"
                    : "Product retrieved successfully. product_id={ProductId}",
                productId);

            return product;
        }

        // ============================================================================
        // 2. GET PRODUCTS BY IDS (BULK)
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Fetch multiple products in one gRPC call
        //   - Used during order creation for pricing & validation
        // ============================================================================
        public async Task<List<ProductDTO>?> GetProductsByIdsAsync(
            List<Guid> productIds,
            string accessToken)
        {
            _logger.LogInformation(
                "Calling ProductService.GetProductsByIds via gRPC. count={Count}",
                productIds.Count);

            // Build protobuf request
            var req = new GetProductsByIdsRequest();
            req.ProductIds.AddRange(productIds.Select(x => x.ToString()));

            // Call gRPC endpoint with auth headers
            var reply = await _client.GetProductsByIdsAsync(
                req,
                headers: BuildHeaders(accessToken));

            _logger.LogInformation(
                "Products retrieved successfully. count={Count}",
                reply.Products.Count);

            // Map protobuf Product → OrderService ProductDTO
            return reply.Products.Select(p => new ProductDTO
            {
                Id = Guid.Parse(p.Id),
                Name = p.Name,

                // string → decimal (InvariantCulture to avoid precision issues)
                Price = decimal.Parse(p.Price, CultureInfo.InvariantCulture),
                DiscountedPrice = decimal.Parse(p.DiscountedPrice, CultureInfo.InvariantCulture),

                StockQuantity = p.StockQuantity
            }).ToList();
        }

        // ============================================================================
        // 3. CHECK PRODUCTS AVAILABILITY
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Validate stock availability before order placement
        //   - High-frequency, performance-critical call
        // ============================================================================
        public async Task<List<ProductStockVerificationResponseDTO>?> CheckProductsAvailabilityAsync(
            List<ProductStockVerificationRequestDTO> requestedItems,
            string accessToken)
        {
            _logger.LogInformation(
                "Calling ProductService.CheckProductsAvailability via gRPC. itemCount={Count}",
                requestedItems.Count);

            // Build protobuf request
            var req = new CheckProductsAvailabilityRequest();
            req.Items.AddRange(requestedItems.Select(i => new StockCheckItem
            {
                ProductId = i.ProductId.ToString(),
                Quantity = i.Quantity
            }));

            // Call gRPC endpoint
            var reply = await _client.CheckProductsAvailabilityAsync(
                req,
                headers: BuildHeaders(accessToken));

            _logger.LogInformation(
                "Stock availability check completed. resultCount={Count}",
                reply.Results.Count);

            // Map protobuf results → OrderService DTOs
            return reply.Results.Select(r => new ProductStockVerificationResponseDTO
            {
                ProductId = Guid.Parse(r.ProductId),
                IsValidProduct = r.IsValidProduct,
                IsQuantityAvailable = r.IsQuantityAvailable,
                AvailableQuantity = r.AvailableQuantity
            }).ToList();
        }

        // ============================================================================
        // 4. INCREASE STOCK (BULK)
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Increase inventory quantities
        //   - Used during order cancellation / returns
        // ============================================================================
        public async Task<bool> IncreaseStockBulkAsync(
            IEnumerable<UpdateStockRequestDTO> stockUpdates,
            string accessToken)
        {
            _logger.LogInformation(
                "Calling ProductService.IncreaseStockBulk via gRPC.");

            var req = new StockBulkUpdateRequest();
            req.Updates.AddRange(stockUpdates.Select(u => new StockUpdate
            {
                ProductId = u.ProductId.ToString(),
                Quantity = u.Quantity
            }));

            var reply = await _client.IncreaseStockBulkAsync(
                req,
                headers: BuildHeaders(accessToken));

            _logger.LogInformation(
                "IncreaseStockBulk completed. success={Success}",
                reply.Success);

            return reply.Success;
        }

        // ============================================================================
        // 5. DECREASE STOCK (BULK)
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Decrease inventory after successful order placement
        // ============================================================================
        public async Task<bool> DecreaseStockBulkAsync(
            IEnumerable<UpdateStockRequestDTO> stockUpdates,
            string accessToken)
        {
            _logger.LogInformation(
                "Calling ProductService.DecreaseStockBulk via gRPC.");

            var req = new StockBulkUpdateRequest();
            req.Updates.AddRange(stockUpdates.Select(u => new StockUpdate
            {
                ProductId = u.ProductId.ToString(),
                Quantity = u.Quantity
            }));

            var reply = await _client.DecreaseStockBulkAsync(
                req,
                headers: BuildHeaders(accessToken));

            _logger.LogInformation(
                "DecreaseStockBulk completed. success={Success}",
                reply.Success);

            return reply.Success;
        }

        // ============================================================================
        // HELPER: BUILD gRPC METADATA HEADERS
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Attach JWT token for authenticated gRPC calls
        //
        // Important:
        //   - gRPC header keys must be lowercase
        // ============================================================================
        private static Metadata BuildHeaders(string accessToken)
        {
            var headers = new Metadata();

            if (!string.IsNullOrWhiteSpace(accessToken))
            {
                headers.Add("authorization", $"Bearer {accessToken}");
            }

            return headers;
        }
    }
}

