using ECommerce.GrpcContracts.Users;
using Grpc.Core;
using Microsoft.Extensions.Logging;
using OrderService.Contracts.DTOs;
using OrderService.Contracts.ExternalServices;

namespace OrderService.Infrastructure.GrpcClients
{
    // ============================================================================
    // gRPC Client Implementation for UserService
    // ----------------------------------------------------------------------------
    // This class:
    //   - Lives in OrderService.Infrastructure
    //   - Implements IUserServiceClient
    //   - Communicates with UserService via gRPC
    //
    // Responsibilities:
    //   - Call UserService gRPC endpoints
    //   - Pass authentication metadata (JWT)
    //   - Map protobuf messages → OrderService DTOs
    // ============================================================================
    public sealed class UserServiceGrpcClient : IUserServiceClient
    {
        private readonly UserGrpc.UserGrpcClient _client;
        private readonly ILogger<UserServiceGrpcClient> _logger;

        // ------------------------------------------------------------------------
        // Constructor
        // ------------------------------------------------------------------------
        // UserGrpcClient is generated by gRPC tooling
        // ILogger is injected by ASP.NET Core
        public UserServiceGrpcClient(
            UserGrpc.UserGrpcClient client,
            ILogger<UserServiceGrpcClient> logger)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        // ============================================================================
        // 1. CHECK IF USER EXISTS
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Lightweight validation before order creation
        //   - Avoid unnecessary work if user is invalid
        // ============================================================================
        public async Task<bool> UserExistsAsync(Guid userId, string accessToken)
        {
            _logger.LogInformation(
                "Calling UserService.UserExists via gRPC. user_id={UserId}",
                userId);

            var reply = await _client.UserExistsAsync(
                new UserExistsRequest
                {
                    // Guid → string (protobuf has no Guid type)
                    UserId = userId.ToString()
                },
                headers: BuildHeaders(accessToken));

            _logger.LogInformation(
                "UserExists completed. user_id={UserId}, exists={Exists}",
                userId, reply.Exists);

            return reply.Exists;
        }

        // ============================================================================
        // 2. GET USER PROFILE BY ID
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Fetch user profile details
        //   - Used during order creation and validation
        // ============================================================================
        public async Task<UserDTO?> GetUserByIdAsync(Guid userId, string accessToken)
        {
            _logger.LogInformation(
                "Calling UserService.GetUserById via gRPC. user_id={UserId}",
                userId);

            var reply = await _client.GetUserByIdAsync(
                new GetUserByIdRequest
                {
                    UserId = userId.ToString()
                },
                headers: BuildHeaders(accessToken));

            // If user not found → return null
            if (!reply.Found || reply.User == null)
            {
                _logger.LogInformation(
                    "User not found in UserService. user_id={UserId}",
                    userId);

                return null;
            }

            _logger.LogInformation(
                "User profile retrieved successfully. user_id={UserId}",
                userId);

            // Map protobuf User → OrderService UserDTO
            return new UserDTO
            {
                Id = Guid.Parse(reply.User.Id),
                FullName = reply.User.FullName,
                Email = reply.User.Email,
                PhoneNumber = reply.User.PhoneNumber
            };
        }

        // ============================================================================
        // 3. GET USER ADDRESS BY ID
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Fetch a specific user address (shipping/billing)
        //   - Used during order placement
        // ============================================================================
        public async Task<AddressDTO?> GetUserAddressByIdAsync(
            Guid userId,
            Guid addressId,
            string accessToken)
        {
            _logger.LogInformation(
                "Calling UserService.GetUserAddressById via gRPC. user_id={UserId}, address_id={AddressId}",
                userId, addressId);

            var reply = await _client.GetUserAddressByIdAsync(
                new GetUserAddressByIdRequest
                {
                    UserId = userId.ToString(),
                    AddressId = addressId.ToString()
                },
                headers: BuildHeaders(accessToken));

            // Address not found
            if (!reply.Found || reply.Address == null)
            {
                _logger.LogInformation(
                    "Address not found. user_id={UserId}, address_id={AddressId}",
                    userId, addressId);

                return null;
            }

            _logger.LogInformation(
                "Address retrieved successfully. user_id={UserId}, address_id={AddressId}",
                userId, addressId);

            // Map protobuf Address → OrderService AddressDTO
            return new AddressDTO
            {
                Id = Guid.Parse(reply.Address.Id),
                UserId = Guid.Parse(reply.Address.UserId),
                AddressLine1 = reply.Address.AddressLine1,
                AddressLine2 =
                    string.IsNullOrWhiteSpace(reply.Address.AddressLine2)
                        ? null
                        : reply.Address.AddressLine2,
                City = reply.Address.City,
                State = reply.Address.State,
                PostalCode = reply.Address.PostalCode,
                Country = reply.Address.Country,
                IsDefaultBilling = reply.Address.IsDefaultBilling,
                IsDefaultShipping = reply.Address.IsDefaultShipping
            };
        }

        // ============================================================================
        // 4. SAVE OR UPDATE USER ADDRESS
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Create or update a user address in UserService
        // ============================================================================
        public async Task<Guid?> SaveOrUpdateAddressAsync(
            AddressDTO addressDto,
            string accessToken)
        {
            _logger.LogInformation(
                "Calling UserService.SaveOrUpdateAddress via gRPC. user_id={UserId}, address_id={AddressId}",
                addressDto.UserId,
                addressDto.Id == Guid.Empty ? "NEW" : addressDto.Id);

            var reply = await _client.SaveOrUpdateAddressAsync(
                new SaveOrUpdateAddressRequest
                {
                    Address = new ECommerce.GrpcContracts.Users.Address
                    {
                        // Empty string indicates "new address"
                        Id = addressDto.Id == Guid.Empty
                                ? string.Empty
                                : addressDto.Id.ToString(),

                        UserId = addressDto.UserId.ToString(),
                        AddressLine1 = addressDto.AddressLine1,
                        AddressLine2 = addressDto.AddressLine2 ?? string.Empty,
                        City = addressDto.City,
                        State = addressDto.State,
                        PostalCode = addressDto.PostalCode,
                        Country = addressDto.Country,
                        IsDefaultBilling = addressDto.IsDefaultBilling,
                        IsDefaultShipping = addressDto.IsDefaultShipping
                    }
                },
                headers: BuildHeaders(accessToken));

            // Convert returned AddressId → Guid
            if (Guid.TryParse(reply.AddressId, out var id))
            {
                _logger.LogInformation(
                    "Address saved successfully. address_id={AddressId}",
                    id);

                return id;
            }

            _logger.LogWarning(
                "SaveOrUpdateAddress returned invalid address_id. value={Value}",
                reply.AddressId);

            return null;
        }

        // ============================================================================
        // HELPER: BUILD gRPC METADATA HEADERS
        // ----------------------------------------------------------------------------
        // Purpose:
        //   - Attach Authorization header for secured gRPC calls
        //
        // Notes:
        //   - gRPC headers must be lowercase
        //   - JWT is passed as Bearer token
        // ============================================================================
        private static Metadata BuildHeaders(string accessToken)
        {
            var headers = new Metadata();

            if (!string.IsNullOrWhiteSpace(accessToken))
            {
                headers.Add("authorization", $"Bearer {accessToken}");
            }

            return headers;
        }
    }
}
